serial: Refactor to properly check for EOF
Clang-Tidy reported warnings like this:

  serial.cc:32:17: error: narrowing conversion from
  'std::basic_istream<char>::int_type' (aka 'int') to signed type 'char'
  is implementation-defined [bugprone-narrowing-conversions]
      while ((c = in.get()) != '&') {
                  ^

I first thought this was a false-positive, but when looking at the
return type of the istream::get() method it actually returns an integer
because it not only returns the actual character but also indicates
whether we've reached EOF.

Instead of using istream::get(), we're now using istream::get(char&) and
check the iostate whether we hit EOF. This not only has the advantage
that we get rid of the lint warning, but we now actually handle EOF
conditions more gracefully (and with better errors).

Signed-off-by: aszlig <aszlig@nix.build>