tests/dynports: Include missing string header
When compiling on Darwin, we get the following error:

  dynports.cc:94:5: error: no member named 'to_string' in namespace 'std'

The <string> header is not included anywhere in the headers leading to
dynports.cc, so I suspect that on glibc the header is implicitly
included.

Adding an explicit inclusion fixes this and of course is also way more
portable.

Signed-off-by: aszlig <aszlig@nix.build>