globpath: Fix OOB access on missing end bracket
When compiling with address sanitiser enabled, we get the following
error during tests:

  ERROR: AddressSanitizer: stack-buffer-overflow on address
                           0x7fffffff61a0 at pc 0x00000041dd5d bp
                           0x7fffffff43f0 sp 0x7fffffff43e8
  READ of size 1 at 0x7fffffff61a0 thread T0
    #0 0x41dd5c in GlobPath::match_cclass(unsigned long*, char const&) ../src/globpath.cc:73
    #1 0x41f0d4 in GlobPath::match() ../src/globpath.cc:237
    #2 0x41f562 in globpath(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&,
                            std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) ../src/globpath.cc:298
    #3 0x40e20c in main ../tests/unit/globpath.cc:24
    #4 0x7ffff720ad8a in __libc_start_main (/nix/store/bwzra330vib0ik4d3l8rq6gp6y2ah1fr-glibc-2.30/lib/libc.so.6+0x23d8a)
    #5 0x41ce79 in _start (/build/source/build/tests/unit/test_globpath+0x41ce79)

The reported issue (#15) has a similar output via Valgrind, but both
boil down to the same problem:

If the end square bracket ("]") is missing for a character class
pattern, the loop doesn't check whether we're overflowing the
std::string_view.

I've fixed this by adding a check which immediately discards the
character class as invalid whenever we hit the end of the pattern.

Signed-off-by: aszlig <aszlig@nix.build>
Reported-by: @etam
Fixes: https://github.com/nixcloud/ip2unix/issues/15